# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://azuresnacks.com/"

title = "Azure Snacks"
languageCode = "en-us"
theme = "codelabs"

[params]
  homeTitle = "Do more with Azure!"
  homeDescription = """
**Azure Snacks** are project-based, step-by-step guides to doing amazing things with Ubuntu. From installing the OS in the first place to packaging your first snap, we're here to help you on your way.

This site is open source and open to contributions from the Linux community, if you have a knack for writing and sharing your knowledge, you can [read our guide](#) to get started.

If you'd like to see a tutorial written on a specific topic, [let us know](#).
"""
  footer = "<a href=\"https://github.com/bketelsen/azuresnacks\">‚ù§ Source code</a>"
  feedbackLink = "mailto:mail@bjk.fyi"
  [params.categoryColors]
    desktop = "#1A73E8"
    server = "#E37400"
    security = "#5F6368"
    irc = "#FFAA00"
